#!/usr/bin/with-contenv sh

# Create configuration files from templates
if [ -f /etc/graylog/server/server.conf.j2 ];then
    j2 /etc/graylog/server/server.conf.j2 > /etc/graylog/server/server.conf
    rm /etc/graylog/server/server.conf.j2
fi
